### ISSUE TITLE
Enable OpenMP support on Linux.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [beltoforion/muparser#3]
```
Hello,

OpenTURNS, an open-source lib dedicated to the treatment of uncertainties, use 
MuParser for some study. By the way, thanks for your work! 
So, for some large study we would like to speed up a little bit the 
computation. So we would like to enable OpenMP inside muParser. 
We know that using a just in time parser would be much faster, but it would 
involve much more work. OpenMP in muParser is the first easy step to speed up 
our code.

I tried to enable OpenMP support on Linux (using autoconf). 
But using the revision 10 of http://muparser.googlecode.com/svn/trunk source, 
if I uncomment the line "#define MUP_USE_OPENMP" it does not enable OpenMP 
compilation  switch and the compilation fails.

I made a patch and the compilation using autoconf runs fine now.
The patch add an --enable-openmp feature (openmp is disabled by default).

  ./configure --enable-openmp
  make
  ...

My system is running on ubuntu 12.04 64bits.

Do you think the patch is good enough? I do not know if it will break 
compilation on other systems (windows ...) as I know only autoconf and cmake.
Could you consider merging this patch to muParser source code?

Beset regards,
Mathieu Souchaud

```

Original issue reported on code.google.com by `mattieu....@free.fr` on 21 Dec 2013 at 5:41

Attachments:
- [muparser_r10-openmp.patch](https://storage.googleapis.com/google-code-attachments/muparser/issue-3/comment-0/muparser_r10-openmp.patch)

**Comment by giraldeau** [comment]
I enabled the OpenMP and added the example1 in a test, but the program gets stuck here: 

```
(gdb) bt
#0  0x00007ffff7b75bb6 in mu::ParserBase::ParseCmdCodeBulk(int, int) const () from /home/francisg/muparser/temp/libmuparser.so.2
#1  0x00007ffff7b79762 in mu::ParserBase::Eval(double*, int) [clone ._omp_fn.0] () from /home/francisg/muparser/temp/libmuparser.so.2
#2  0x00007ffff6ca7cbf in GOMP_parallel () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#3  0x00007ffff7b795ab in mu::ParserBase::Eval(double*, int) () from /home/francisg/muparser/temp/libmuparser.so.2
#4  0x00007ffff7baf41b in mu::Test::ParserTester::EqnTestBulk(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double*, bool) ()
   from /home/francisg/muparser/temp/libmuparser.so.2
#5  0x00007ffff7b94f77 in mu::Test::ParserTester::TestBulkMode() () from /home/francisg/muparser/temp/libmuparser.so.2
#6  0x00007ffff7baaa86 in mu::Test::ParserTester::Run() () from /home/francisg/muparser/temp/libmuparser.so.2
#7  0x000000000040bac9 in SelfTest() ()
#8  0x000000000040dbfe in main ()
```

**Comment by beltoforion** [comment]
Can confirm that there seems to be an issue but not yet what kind of issue. Will investigate the issue.

**Comment by beltoforion** [comment]
The reason is that the bulk test code is using a sample size of 4. Nowadays most cpu's have more cors and due to an error in the chuck size computation for openmp. The parser is assigning a chunk size of 0.

A fix will be commited shortly.

**Comment by beltoforion** [comment]
The issue is fixed; OpenMP is now the default setting for compiling muparser
